faq/urls.py
from django.conf.urls import patterns, include, url

from faq import views

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.ListarFaq.as_view(), name='listar_faq'),
    url(r'^novo$', views.CriarFaq.as_view(), name='criar_faq'),
    url(r'^editar/(?P<pk>\d+)$', views.AlterarFaq.as_view(), name='alterar_faq'),
    url(r'^deletar/(?P<pk>\d+)$', views.DeletarFaq.as_view(), name='deletar_faq'),
)

portalfaq/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^faq/', include('faq.urls', namespace='faq')),
    url(r'^$', 'portalfaq.views.home'),
)

faq/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Faq(models.Model):
    pergunta = models.CharField(max_length = 200)
    resposta = models.CharField(max_length = 200)
    data = models.DateField()

    def __unicode__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse ('faq:editar_faq', kwargs={'pk':self.pk})

faq/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from faq.models import Faq

class ListarFaq(ListView):
    model = Faq

class CriarFaq(CreateView):
    model = Faq
    fields = ['pergunta', 'resposta', 'data']
    success_url = reverse_lazy('faq:listar_faq')

class AlterarFaq(UpdateView):
    model = Faq
    fields = ['pergunta', 'resposta', 'data']
    success_url = reverse_lazy('faq:listar_faq')

class DeletarFaq(DeleteView):
    model = Faq
    fields = ['pergunta', 'resposta', 'data']
    success_url = reverse_lazy('faq:listar_faq')

portalfaq/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

def home(request):
	html = """
	<h1>Faq Portal de Ideias</h1>
	<a href="/faq/">Faq</a><br>
	"""

	return HttpResponse(html)

faq/templates/faq/faq_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Tem certeza que deseja deletar a pergunta "{{ object.pk }}"?</p>
    <input type="submit" value="Sim" />
</form>

faq/templates/faq/faq_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Criar" />
</form>

faq/templates/faq/faq_list.html
<h1>Faq</h1>
<ul>
    {% for faq in object_list %}
        <li>Pergunta: {{ faq.pergunta }}</li>
        <li>Resposta: {{ faq.resposta }}</li>
        <li>Data: {{ faq.data }}</li>
            <a href="{% url 'faq:alterar_faq' faq.pk %}">Editar</a>
            <a href="{% url 'faq:deletar_faq' faq.pk %}">Deletar</a>
    {% empty %}
        <li>Não existem perguntas frequentes</li>
{% endfor %}
</ul>
<a href="{% url 'faq:criar_faq' %}">Novo</a>